### ISSUE TITLE
Dependency Conflict: pymongo==4.4.1 with umongo 3.1.0 and motor 3.3.1/3.4.0

### ISSUE THREAD

**Issue by DreamXBotz** [MrMKN/Professor-bot#110]
I'm encountering a dependency conflict while trying to use pymongo==4.4.1 with umongo 3.1.0 and motor 3.3.1 or motor 3.4.0. The error occurs during the installation process and is causing a failure in my Docker build. 

Trying different versions of motor (e.g., 3.3.1, 3.4.0) but still encountering conflicts.

Could you please provide guidance on compatible versions of umongo and motor that work with pymongo==4.4.1? Any advice or suggestions on resolving this dependency conflict would be greatly appreciated.

**Comment by Monarchsenpai** [comment]
Yhaa change motor==3.3.1 to motor==3.2.0
