### ISSUE TITLE
Koyeb Error: failed to build: exit status 1

### ISSUE THREAD

**Issue by JeevabharathiRK** [MrMKN/Professor-bot#121]
![image](https://github.com/user-attachments/assets/5e97bcce-350b-48fe-a2fe-d9226c3cdae9)
_**error while deploying the app. It may occurs due to the conflicts in requested versions in requirements.py**_

**Comment by Youngkiddo1** [comment]
Fork the repo then in requirements.txt edit the pymongo version to 4.5

**Comment by Youngkiddo1** [comment]
Then build from your fork
