### ISSUE TITLE
Add files 

### ISSUE THREAD

**Issue by Youngkiddo1** [MrMKN/Professor-bot#123]
How can I add movie files to the bot without downloading and uploading? You have a very nice project tho. Thanks

**Comment by MrMKN** [comment]
use index method, collect files form telegram and forward to your private channel and make bot admin in that channel then forward last message from that channel to your bot and index. you can also index from public channel files, just forward last message from channel to bot. and you can also use last message link form tha channel and paste to bot, bot will ask to you for index (useful in forward restricted channel). Thanks For your support ✨
