### ISSUE TITLE
Error On Deployment

### ISSUE THREAD

**Issue by sakthiraj2008** [MrMKN/Professor-bot#124]
I Was Fork And Deploy On Koyeb But Build Was Completed But Deployment Was Error
![Screenshot_2024-10-23-06-20-38-146_com android chrome](https://github.com/user-attachments/assets/12dd70c9-076d-4f53-8c38-2e6f1f5763ca)

**Comment by MrMKN** [comment]
Check your url to correct format like:  "mongodb+srv://username:password@cluster0.abcdefg.mongodb.net/?retryWrites=true&w=majority"
