### ISSUE TITLE
Professor Bot not working upon giving movie request 

### ISSUE THREAD

**Issue by BucketLizzt** [MrMKN/Professor-bot#125]
I know that this is really not the place to discuss matters like this... But I have no other choice... So basically the thing is for a few days now.. The professor bot is not responding to my movie request at all.. I reinstalled telegram and other stuff.. Still it is not working pls do help

**Comment by MrMKN** [comment]
Your issue is related for our bot? Please contact our support group on telegram https://t.me/MKN_BOTZ_DISCUSSION_GROUP 
Or Your issue related to thi repo? please explain (which error or send screen shot)
