### ISSUE TITLE
Batch File Problem 

### ISSUE THREAD

**Issue by RbY-Rj** [MrMKN/Professor-bot#29]
Generating Link for batch files is not working......
![IMG_20230308_071436](https://user-images.githubusercontent.com/96897008/223597745-5155f7fe-11db-4add-b557-8a3872917e71.jpg)

**Comment by MrMKN** [comment]
any error in logs

**Comment by MrMKN** [comment]
check your log channel batch.json

**Comment by RbY-Rj** [comment]
Ook bro thank you ❤️
