### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dev-Khrish** [MrMKN/Professor-bot#30]
Bot script is on in heroku but bot in telegram not working

**Comment by MrMKN** [comment]
Which error showing?

**Comment by Dev-Khrish** [comment]
no errors the script started but bot didnt started idk why pls help and when i click on the web i got this error

![image](https://user-images.githubusercontent.com/106378292/224790290-5a187888-f3cd-4ba0-8d56-166f67fab615.png)
 
 
 if you can then msg me on telegram please it will me more faster then this my username @SpidyRockss
